import os
import logging

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VQG Study Guide — {filename}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">
    <style>
        :root {{
            --primary: #6366f1;
            --primary-hover: #4f46e5;
            --bg: #0f172a;
            --card-bg: #1e293b;
            --text: #f8fafc;
            --text-muted: #94a3b8;
            --accent: #22d3ee;
            --success: #22c55e;
        }}

        * {{ box-sizing: border-box; margin: 0; padding: 0; }}

        body {{
            font-family: 'Inter', sans-serif;
            background-color: var(--bg);
            color: var(--text);
            line-height: 1.6;
            padding: 2rem;
            display: flex;
            flex-direction: column;
            align-items: center;
        }}

        header {{
            text-align: center;
            margin-bottom: 3rem;
            max-width: 800px;
        }}

        h1 {{
            font-size: 2.5rem;
            font-weight: 700;
            background: linear-gradient(135deg, var(--primary), var(--accent));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 0.5rem;
        }}

        .stats {{
            font-size: 0.9rem;
            color: var(--text-muted);
            text-transform: uppercase;
            letter-spacing: 0.1em;
        }}

        .quiz-container {{
            width: 100%;
            max-width: 900px;
            display: grid;
            gap: 2rem;
        }}

        .quiz-card {{
            background: var(--card-bg);
            border-radius: 1.5rem;
            padding: 2rem;
            box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
            border: 1px solid rgba(255, 255, 255, 0.05);
            transition: transform 0.2s ease;
        }}

        .quiz-card:hover {{
            transform: translateY(-4px);
        }}

        .question-header {{
            margin-bottom: 1.5rem;
            font-size: 1.1rem;
            font-weight: 600;
            color: var(--accent);
        }}

        .image-container {{
            position: relative;
            background: #000;
            border-radius: 1rem;
            overflow: hidden;
            margin-bottom: 1.5rem;
            cursor: pointer;
        }}

        .image-container img {{
            width: 100%;
            display: block;
            transition: opacity 0.3s ease;
        }}

        .answer-overlay {{
            position: absolute;
            top: 0; left: 0; width: 100%; height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            background: rgba(15, 23, 42, 0.8);
            opacity: 0;
            transition: opacity 0.3s ease;
            backdrop-filter: blur(4px);
            padding: 2rem;
            text-align: center;
        }}

        .quiz-card.revealed .answer-overlay {{
            opacity: 1;
        }}

        .quiz-card.revealed img {{
            opacity: 0.3;
        }}

        .answer-content h2 {{
            font-size: 1.8rem;
            margin-bottom: 1rem;
            color: var(--success);
        }}

        .explanation {{
            font-size: 0.95rem;
            color: var(--text-muted);
        }}

        .controls {{
            display: flex;
            gap: 1rem;
            margin-top: 1rem;
        }}

        button {{
            padding: 0.75rem 1.5rem;
            border-radius: 0.75rem;
            border: none;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.2s ease;
            font-family: inherit;
        }}

        .btn-primary {{
            background: var(--primary);
            color: white;
        }}

        .btn-primary:hover {{ background: var(--primary-hover); }}

        .distractors {{
            margin-top: 1rem;
            font-size: 0.85rem;
            color: var(--text-muted);
            font-style: italic;
        }}

        footer {{
            margin-top: 5rem;
            color: var(--text-muted);
            font-size: 0.8rem;
        }}
    </style>
</head>
<body>
    <header>
        <h1>Study Guide</h1>
        <div class="stats">{filename} • {card_count} Flashcards</div>
    </header>

    <div class="quiz-container">
        {cards_html}
    </div>

    <footer>
        Generated by VQG — Visual Quiz Generator
    </footer>

    <script>
        function toggleAnswer(btn) {{
            const card = btn.closest('.quiz-card');
            // Image cards use the .revealed CSS class for the overlay
            const answerDiv = card.querySelector('.answer-content');
            if (answerDiv && answerDiv.style.display !== undefined && !card.querySelector('.image-container')) {{
                // Text-only card
                const revealed = answerDiv.style.display === 'block';
                answerDiv.style.display = revealed ? 'none' : 'block';
                btn.textContent = revealed ? 'Show Answer' : 'Hide Answer';
            }} else {{
                // Image card
                card.classList.toggle('revealed');
                btn.textContent = card.classList.contains('revealed') ? 'Show Question' : 'Show Answer';
            }}
        }}
    </script>
</body>
</html>
"""

CARD_TEMPLATE = """
<div class="quiz-card" id="card-{id}">
    <div class="question-header">{question}</div>
    <div class="image-container" onclick="toggleAnswer(this.nextElementSibling)">
        <img src="{image_url}" alt="Quiz Diagram">
        <div class="answer-overlay">
            <div class="answer-content">
                <h2>{answer}</h2>
                <p class="explanation">{explanation}</p>
                <div class="distractors">Distractors: {distractors}</div>
            </div>
        </div>
    </div>
    <div class="controls">
        <button class="btn-primary" onclick="toggleAnswer(this)">Show Answer</button>
    </div>
</div>
"""

# Text-only card — no image (used for CONTEXT_MCQ items)
CARD_TEMPLATE_TEXT = """
<div class="quiz-card" id="card-{id}">
    <div class="question-header">{question}</div>
    <div class="controls">
        <button class="btn-primary" onclick="toggleAnswer(this)">Show Answer</button>
        <div class="answer-content" style="display:none; margin-top:1rem;">
            <h2 style="color:var(--success); font-size:1.4rem; margin-bottom:0.75rem;">{answer}</h2>
            <p class="explanation">{explanation}</p>
            <div class="distractors">Distractors: {distractors}</div>
        </div>
    </div>
</div>
"""

def build_html_export(results: list[dict], job_id: str, pdf_filename: str) -> str:
    from backend.config import EXPORTS_PATH, IMAGES_PATH, STORAGE_PATH
    
    cards_html_list = []
    card_count = 0
    
    # We want to use absolute paths for the generator, but the HTML will use relative paths
    # or embedded images? Let's try relative to the exports folder.
    
    for item_idx, item in enumerate(results):
        questions = item.get("questions")
        if not questions:
            continue

        # Text-only cards (CONTEXT_MCQ, TEXT_MCQ) carry no image
        is_context_mcq = item.get("method") in ("context_mcq", "text_mcq")

        if is_context_mcq:
            image_path = None
        else:
            image_path = item.get("processed_path") or item.get("image_path")

        for q_idx, q in enumerate(questions):
            card_id = f"{item_idx}-{q_idx}"
            common = dict(
                id=card_id,
                question=q.get("question", "Identify the highlighted structure:"),
                answer=q.get("structure_name", "Unknown"),
                explanation=q.get("explanation", ""),
                distractors=", ".join(q.get("distractors", [])),
            )
            if image_path:
                rel_to_storage = os.path.relpath(image_path, start=STORAGE_PATH).replace("\\", "/")
                image_url = "../../" + rel_to_storage
                cards_html_list.append(CARD_TEMPLATE.format(image_url=image_url, **common))
            else:
                cards_html_list.append(CARD_TEMPLATE_TEXT.format(**common))
            card_count += 1

    final_html = HTML_TEMPLATE.format(
        filename=pdf_filename,
        card_count=card_count,
        cards_html="\\n".join(cards_html_list)
    )
    
    job_exports_dir = os.path.join(EXPORTS_PATH, job_id)
    os.makedirs(job_exports_dir, exist_ok=True)
    output_path = os.path.abspath(os.path.join(job_exports_dir, "study_guide.html"))
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(final_html)
        
    logger.info("build_html_export: wrote %d cards to %s", card_count, output_path)
    return output_path
